USE DatabaseAssigment;

CREATE TABLE ShoppingCarts(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	_Name NVARCHAR(10)
);

CREATE TABLE Products(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	_Name NVARCHAR(30) NOT NULL,
	_Description NVARCHAR(100),
	Price FLOAT NOT NULL,
	Raiting FLOAT NOT NULL,
);


CREATE TABLE Customers (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(30) NOT NULL,
    LastName NVARCHAR(30)  NOT NULL,
    Email NVARCHAR(30)  NOT NULL,
	_Password NVARCHAR(30)  NOT NULL,
	Phone NVARCHAR(10)  NOT NULL,
	Adress NVARCHAR(50),
	ShoppingCartId INT  NOT NULL FOREIGN KEY REFERENCES ShoppingCarts(Id)
);

CREATE TABLE ShoppingCartsProducts(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ShoppingCartId INT NOT NULL FOREIGN KEY REFERENCES ShoppingCarts(Id),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id)
);



